version: '3'
services:
  pokechill:
    image: nightis/pokechill-docker:latest
    container_name: pokechill
    ports:
      - "3000:3000"
    volumes:
      # This maps a local 'pokechill_data' directory to the container's data directory.
      # Your database (pokechill.db) will be stored here and visible on the host.
      - ./pokechill_data:/data
      # This maps a local 'saves' directory to the container's saves directory for easy access
      - ./saves:/usr/src/app/saves
    restart: always
